version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.2-apache-stretch-node-browsers
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_HOST: 127.0.0.1
          DB_HOST: 127.0.0.1
          DB_NAME: phalcon_base_project_test
          DB_USERNAME: myuser
          DB_PASSWORD: password
          CLIENT_SECRET: client_secret
          CLIENT_ID: client_id

    steps:
      - checkout
      - run:
          name: Install Mysql & Dependencies
          command: |
            sudo apt-get update
            sudo apt-get install mysql-client
            sudo apt-get install -y mysql-server

      - run:
          name: Install PHP extensions
          command: |
            sudo docker-php-ext-install zip
            sudo docker-php-ext-configure intl
            sudo docker-php-ext-install intl
            sudo docker-php-ext-install pdo_mysql

      - run:
          name: Fix MySQL socket config
          command: |
            sudo sh -c "echo 'pdo_mysql.default_socket=/var/run/mysqld/mysqld.sock' > /usr/local/etc/php/conf.d/pdo.ini"

      - run:
          name: Start database server
          command: |
            sudo service mysql start

      - run:
          name: Create non-admin user
          command: |
            sudo mysql -u root -e "CREATE user myuser IDENTIFIED BY 'password';"
            sudo mysql -u root -e "GRANT ALL ON *.* to myuser@'%' IDENTIFIED BY 'password';"
            sudo mysql -u root -e "FLUSH PRIVILEGES;"

      - run:
          name: Install Phalcon
          command: |
            git clone https://github.com/yemexx1/phalcon-switcher.git
            cd phalcon-switcher
            chmod +x phalcon-switcher.sh
            sudo ln -s `pwd`/phalcon-switcher.sh /usr/local/bin/phalcon-switcher
            sudo phalcon-switcher 3.3.2

      - run:
          name: Run Composer Install
          command: |
            cd ~/project
            composer config -g github-oauth.github.com $GITHUB_TOKEN
            composer install

      - run:
          name: Create env file
          command: |
            mv env/.env.circleci env/.env.test
            chmod -R 777 App/logs

      - run:
          name: Install Ant Build
          command: |
            sudo apt-get install ant
            ant build

      - run:
          name: Run Test
          command: |
            sh ./runtest.sh
